name: freelancing_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  bloc: ^8.1.2
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_styled_toast: ^2.2.1
  google_fonts: ^6.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/design/images/

fonts:
  - family: SFProText
    fonts:
      - asset: fonts/SFProText-Regular.ttf
        weight: 400
      - asset: fonts/SFProText-Bold.ttf
        weight: 700
